namespace QuickJSharp.Bindings;

/// <summary>
/// Marks a class as a registry for JavaScript bindings generated by
/// <c>QuickJSharp.Bindings.Generators</c>.
/// </summary>
/// <remarks>
/// The marked class must extend <see cref="BindingExtension"/> and be <c>partial</c>,
/// declaring the following constructor which the source generator will implement:
/// <code>
/// public partial MyRegistry();
/// </code>
/// The generator will implement this constructor to register all bindings targeting
/// this registry. Each instance is independent and safe to add to a single
/// <see cref="JSRuntime"/>. To use the same bindings across multiple runtimes,
/// construct a new instance per runtime.
/// </remarks>
/// <seealso cref="BindingExtension"/>
/// <seealso cref="JSNamingConvention"/>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class JSBindingsRegistryAttribute : Attribute { }
