using QuickJSharp.Bindings.Generators.Models;

namespace QuickJSharp.Bindings.Generators.Emitters;

static class BindingEmitter
{
    public static string Emit(ExposedType exposedType, Registry registry)
    {
        if (exposedType.Kind == ExposedTypeKind.Enum)
        {
            return EnumBindingEmitter.Emit(exposedType, registry);
        }

        return $$"""
// <auto-generated/>
#nullable enable

// Binding for {{exposedType.DotnetType}} targeting {{registry.DotnetType}}
""";
    }
}
