using System.Text;
using QuickJSharp.Bindings.Generators.Models;

namespace QuickJSharp.Bindings.Generators.Emitters;

static class EnumBindingEmitter
{
    public static string Emit(ExposedType exposedType, Registry registry)
    {
        var registryType = registry.DotnetType;
        var enumType = exposedType.DotnetType;

        var members = new StringBuilder();
        foreach (var member in exposedType.Members)
        {
            if (member.Kind is not (ExposedMemberKind.Field or ExposedMemberKind.Const))
            {
                continue;
            }

            members.AppendLine($"            (\"{member.JSName}\", (long){enumType}.{member.DotnetName}),");
        }

        return $$"""
// <auto-generated/>
#nullable enable

file sealed class Binding : global::QuickJSharp.Bindings.EnumBinding
{
    {{BindingConstants.ModuleInitializer}}
    internal static void Initialize()
    {
        {{registryType}}.Register(reg => new Binding(reg));
    }

    public Binding(global::QuickJSharp.Bindings.BindingsRegistry registry)
        : base(registry, "{{exposedType.JSName}}", [
{{members}}
        ])
    {
    }
}
""";
    }
}
