using QuickJSharp.Bindings.Generators.Models;

namespace QuickJSharp.Bindings.Generators.Emitters;

static class RegistryEmitter
{
    public static string Emit(Registry registry)
    {
        var ns = registry.Namespace is null ? string.Empty : $$"""namespace {{registry.Namespace}};""";

        return $$"""
// <auto-generated/>
#nullable enable

{{ns}}

partial class {{registry.ClassName}}
{
    private static readonly global::System.Collections.Generic.List<global::System.Func<global::QuickJSharp.Bindings.BindingsRegistry, global::QuickJSharp.Bindings.BindingBase>> _generatedFactories = [];

    {{BindingConstants.AggressiveInlining}}
    internal static void Register(global::System.Func<global::QuickJSharp.Bindings.BindingsRegistry, global::QuickJSharp.Bindings.BindingBase> factory)
    {
        _generatedFactories.Add(factory);
    }

    public partial {{registry.ClassName}}() : base(_generatedFactories)
    {
    }
}
""";
    }
}
